spring:
  name: codeProject
  redis:
    host: 127.0.0.1  # Redis??
    port: 6379       # ??
    password:        # ??????
    lettuce:
      pool:
        max-active: 50  # ??????????40?
        max-idle: 20    # ??????
        min-idle: 5     # ??????
server:
  port: 8080 # ????

